@echo off
cd /d "%~dp0"
echo Installing dependencies...
call npm install
echo Building...
call npx tsup src/index.ts --format cjs,esm --dts --clean
echo Adding to git...
git add .gitignore dist/
echo Committing...
git commit -m "chore: include dist folder for GitHub npm installs"
echo Pushing...
git push origin master-node
echo Done!
pause
